Task sometimes fails on Windows due to failure to move temp buffer to final output. Cause unknown. Workaround: warn when temp buffers are left behind, but don't crash the task.
java.io.IOException: Failed to delete original file 'C:\\Users\\foobar\\AppData\\Local\\Temp\\SejdaTmpBuffer3301971305492379955.pdf' after copy to 'C:\\Users\\foobar\\AppData\\Local\\Temp\\tmp-7848Bo3NF80kcSIi\\sample_file.pdf
at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2996)
at org.sejda.core.support.io.OutputWriterHelper.moveFile(OutputWriterHelper.java:151)
at org.sejda.core.support.io.OutputWriterHelper.moveToDirectory(OutputWriterHelper.java:115)
at org.sejda.core.support.io.BaseOutputWriter.dispatch(...)