ImagesToPdfDocumentConverter.getImagePageCount() can fail due to other exceptions, eg: HuffmanTable cannot be read of JPEG. Ensure this is not breaking the task and default to 1.
java.lang.ArrayIndexOutOfBoundsException: Index 200 out of bounds for length 200
                                                                                       	at com.twelvemonkeys.imageio.plugins.jpeg.HuffmanTable.read(HuffmanTable.java:164)