Don't fail the crop task because form handling failed:
java.lang.IllegalArgumentException: /DA is a required entry
	at org.sejda.sambox.pdmodel.interactive.form.PDDefaultAppearanceString.(PDDefaultAppearanceString.java:82)
	at org.sejda.sambox.pdmodel.interactive.form.PDVariableText.getDefaultAppearanceString(PDVariableText.java:93)
	at org.sejda.sambox.pdmodel.interactive.form.AppearanceGeneratorHelper.(AppearanceGeneratorHelper.java:92)
	at org.sejda.sambox.pdmodel.interactive.form.PDTextField.constructAppearances(PDTextField.java:263)
	at org.sejda.sambox.pdmodel.interactive.form.PDAcroForm.refreshAppearances(PDAcroForm.java:251)
	at org.sejda.sambox.pdmodel.interactive.form.PDAcroForm.flatten(PDAcroForm.java:146)
	at org.sejda.impl.sambox.component.AcroFormsMerger.flatten(AcroFormsMerger.java:292)